theme: jekyll-theme-slate
show_downloads: True

title: Topology Optimization through Neural Networks
description: Aaron Slavin (<a href="ads5825@psu.edu">ads5825@psu.edu</a>) <br>Ibrahim Takroni (<a href="ima5170@psu.edu">ima5170@psu.edu</a>) <br>Zachary Timothy (<a href="znt5009@psu.edu">znt5009@psu.edu</a>)
